model = "gpt-5.5"
model_provider = "openai"
model_reasoning_effort = "xhigh"
disable_response_storage = true
approvals_reviewer = "user"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"

[model_providers.zetatechs]
name = "zetatechs"
base_url = "https://api.zetatechs.com/v1"
wire_api = "responses"
env_key = "ZETATECHS_API_KEY"

[projects."/home/gaivr/research/HKUST/BSR_Bench"]
trust_level = "trusted"

[projects."/home/gaivr/research/HKUST/BraveHeartsBCI/rtca-eeg"]
trust_level = "trusted"

[projects."/home/gaivr/.codex"]
trust_level = "trusted"

[projects."/home/gaivr/programs/rust/BQG"]
trust_level = "trusted"

[projects."/home/gaivr/programs/gambling/pachinko"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
gpt-5-codex = "gpt-5.4"

[tui.model_availability_nux]
"gpt-5.5" = 4

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PERSONAL_ACCESS_TOKEN"

[mcp_servers.alphaXiv]
url = "https://api.alphaxiv.org/mcp/v1"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[hooks.state]

[hooks.state."/home/gaivr/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:da5371beab668efc3d4387486e8a236e08d97ca6bd4c0f29958e6711ede61b02"

[hooks.state."/home/gaivr/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:81419e2061b66f80e8a0ee8b36db96a5d886e1b5ac76df5c91572d3d71d93aac"

[hooks.state."/home/gaivr/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:7fc26e95e904cad995a672ffbb37fae39d2bde2cc793a6dab0011f7de9b83775"

[hooks.state."/home/gaivr/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:acb981547c9259751906dcb92c90e02fd71acd02ffdb1fe48dc22ffe4aca84de"

[features]
terminal_resize_reflow = true
